# Generated by Django 6.0.5 on 2026-06-02 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('dias_sem_comprar', models.IntegerField(default=0)),
                ('total_gasto_mes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria_mais_comprada', models.CharField(choices=[('Mercearia', 'Mercearia'), ('Vegetariano e Saudavel', 'Vegetariano e Saudável'), ('Fraldas e Infantil', 'Fraldas e Infantil'), ('Hortifruti', 'Hortifruti'), ('Bebidas e Cervejas', 'Bebidas e Cervejas'), ('Limpeza', 'Limpeza'), ('Padaria', 'Padaria'), ('Acougue e Peixaria', 'Açougue e Peixaria'), ('Feriados e Doces', 'Feriados e Doces'), ('Limgue e Peixaria', 'Linguiça e Peixaria')], max_length=50)),
                ('perfil', models.CharField(choices=[('ex_fiel', 'Ex-Fiel (Risco de Churn)'), ('vegetariano_incompleto', 'Vegetariano Incompleto (Cross-Sell)'), ('habitos_previsiveis', 'Hábitos Previsíveis (Bebê)'), ('ativo', 'Cliente Ativo'), ('novo', 'Cliente Novo')], default='ativo', max_length=30)),
                ('status', models.CharField(choices=[('vermelho', 'Vermelho - Alto Risco'), ('amarelo', 'Amarelo - Atenção'), ('verde', 'Verde - Saudável')], default='verde', max_length=10)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('push', 'Notificação Push'), ('cupom', 'Cupom de Desconto'), ('email', 'E-mail Personalizado'), ('sms', 'SMS')], default='push', max_length=10)),
                ('mensagem', models.TextField()),
                ('oferta', models.CharField(blank=True, max_length=200)),
                ('desconto', models.IntegerField(default=0)),
                ('categoria_alvo', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('lida', 'Lida')], default='pendente', max_length=10)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
